### ISSUE TITLE
Github missing files or referencing missing names

### ISSUE THREAD

**Issue by djcyberdad** [sjgray/cbm-transfer#5]
CBMxfer.txt, which I assume is for 1.24, the newest version only by the upload date and notes, references a "setup.exe" that does not exist in this repository. There IS a setup.exe for the 1.0 version, who's file date in the zip is from 1998.   I correctly guessed (???) that I have to put all the files from the github in the same folder as Open cbm?  This references programs ALSO used by vice, so do I need to duplicate programs from there to this directory, or should I install it there? Can I only copy the .exe file and it still work?
There are many files that appear to be from old versions, but are not labeled as such. Do I need to keep all the files and folders? There is a lot of clutter here and,  I, an established, practiced idiot, (not licenced or insured however) feel pulled in many directions by the implicated usage and non-direct instructions.

**Comment by djcyberdad** [comment]
I get runtime error 75 everytime I exit the program, I had to turn on the "check for EXE's" for it to tell me I need the cbmlink.exe program, which apparently is not in opencbm directory. I'm not sure why all these necessary exe's weren't included in an updated installation zip or folder. Or why every file from every old version is included as well.  It probably only seems like that because I am an idiot, but it still makes me think I'm doing this incorrectly

**Comment by djcyberdad** [comment]
ok, the cbmlink-0.97.tar.gz.... DOESN'T HAVE CBMLINK.EXE IN IT!  what the hell man?

**Comment by djcyberdad** [comment]
...ok if i'm reading this correctly, the cbmlink website says I have to....learn hex and compile my own? I am learning to hate programmers more in new ways every day.  It is very exasperating to search through all these poorly named zip files on this person's website for an exe that apparently hasn't changed since 2009, to make a software front end, for a herd of squirrels and exe's and bats from every corner of the earth to make a device from 2011 work. 
I'm fairly certain these files could have been put in the same place  to begin with.

**Comment by djcyberdad** [comment]
I did not mean to close this. DAMN I'm great at this idiot thing.

**Comment by djcyberdad** [comment]
ah. the ol' "you have to read the entire text before you do stuff" once again. This is difficult for me because of the extremely limited real estate in my brain.

WAIT, NO THIS STILL DOESNT TELL ME ANYTHING,
" f you want to use IEEE drives, copy the "CBMLINK.EXE" file there too. Finally, if you have a Zoom Floppy
  with parallel cable copy the NibTools EXE files (nibread, nibwrite, nibconv) and/or the ImgCopy utility as well.  JUST INCLUDE IT IN THE ZIP!!! IT'S FREE!!!!

**Comment by djcyberdad** [comment]
i have downloaded 5 compressed files from this "cbm link" chucklefuck's site AND NONE OFTHEM CONTAIN CBMLINK.EXE...
WHAT IS THIS?

**Comment by djcyberdad** [comment]
oh my god it's working, i have no idea what I did, but I think it had to do with the program files directory VS the unzipped folder directory...

I'm still confused.... it's 6am i'm exhausted.

**Comment by djcyberdad** [comment]
I'm sorry I did this to your github, but I also feel my strife must be observed.

**Comment by sjgray** [comment]
I am glad it is finally working! Sorry for your struggles. Where did your journey start? At Github, my webpage, or some other location? It seems like you are following a map without a destination in mind.

 CBM-Transfer is a GUI not a complete solution. I can't include the command-line utilities because I did not write them, do not support them, do not maintain them, and do not have the rights to include them. I realize this can be a confusing situation. I try to make the documentation and my website as helpful as I can. Github is not for the typical end user. You should be looking at the website for info and files.

 First, you do not need ALL the command utilities. Most people will not need CBM-LINK, MD5 or ACME. You will need OpenCBM and C1541.EXE (which is part of VICE).  After you install and test that OpenCBM is working with your disk drive, you can then copy any commandline utilities you need. After that install the complete CBM-Transfer release with the SETUP file, install to the OpenCBM folder. It should work.

 If you want a newer CBM-Transfer you can download an updated version from my website and copy all the files from the ZIP into the OpenCBM folder. I would only recommend Github if you want to use a new feature that has been added. I sometimes update github with small additions or fixes that might not be relevant to your usage so you wouldn't necessarily need to be up to date. I do not always update my webpage to keep up with my github releases... most people don't need to worry about them.

If you have any other issues please email me ;-)

**Comment by sjgray** [comment]
I have updated the website to address some of your issues. Also, further it is not necessary to copy all the github files unless you want to play with the source code in VisualBASIC. I use VisualBASIC to create the FULL release with SETUP.EXE. I will add the releases to github for those that want to download just the program without sourcecode.

**Comment by djcyberdad** [comment]
What a wonderful thoughtful response. Although I'll have to go through it
and full detail later, thank you so much.
